name: 🚀 Sugerir uma nova funcionalidade
description: Utilize esse formato de issue para sugerir uma nova funcionalidade.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: '# Sugestão de recurso'

  - type: textarea
    id: description
    attributes:
      label: Descrição da sugestão
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Como implementar?
      description: Tem alguma sugestão de como isso pode ser implementado?
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Mídia, se aplicável
      description: Screenshot, vídeo, GIF, dentre outros, que ajudem a demonstrar a sugestão.
    validations:
      required: false