name: add-post

on:
  workflow_dispatch:
    inputs:
      social:
        description: "The social media this content belongs to"
        required: true
        default: 'twitter'
        type: choice
        options:
          - twitter
          - instagram
          - youtube
      tweetUrl:
        description: "Url of the tweet to be added"
        required: true
        type: string
      title:
        description: "You can override the post's title"
        required: false
      description:
        description: "You can override the post's description"
        required: false

jobs:
  run-post-script:
     # Create a ubuntu virtual machine
    runs-on: ubuntu-latest

    # Checkout repo code
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.POST_PAT }}

    # Install node
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: npm install puppeteer

    - name: Runs post script
      run: npm run addpost ${{ github.event.inputs.tweetUrl }} -- --title="${{ github.event.inputs.title }}" --description="${{ github.event.inputs.description }}" --social="${{ github.event.inputs.social }}"

    # Commit changes
    - name: Commit and push if changed
      run: |-
        git config --global user.email "nickgabe@manager.com"
        git config --global user.name "Post Manager"
        git add -A
        git commit -m "Adds new post" || exit 0
        git push